// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web; // Linux usa as mesmas opções da Web
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKMzehywMTCiKhkl2aQpo4crxprxnUu-U',
    appId: '1:237814584611:web:728c33870db3acc50ee896',
    messagingSenderId: '237814584611',
    projectId: 'quantum-guard-8bddf',
    authDomain: 'quantum-guard-8bddf.firebaseapp.com',
    storageBucket: 'quantum-guard-8bddf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCverqmICcdo8otW1mV7lcw1L40a-Ns22k',
    appId: '1:237814584611:android:94331c964b85efd70ee896',
    messagingSenderId: '237814584611',
    projectId: 'quantum-guard-8bddf',
    storageBucket: 'quantum-guard-8bddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdmbIx0zvO-dVI5Ckql25D_hOaq6lwopU',
    appId: '1:237814584611:ios:e430d41246b129f90ee896',
    messagingSenderId: '237814584611',
    projectId: 'quantum-guard-8bddf',
    storageBucket: 'quantum-guard-8bddf.firebasestorage.app',
    androidClientId: '237814584611-7b336lhvtl59id5oicuh7i7ddd1594m1.apps.googleusercontent.com',
    iosClientId: '237814584611-him275523db7373jbcuo9mn47o3mkiqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdmbIx0zvO-dVI5Ckql25D_hOaq6lwopU',
    appId: '1:237814584611:ios:e430d41246b129f90ee896',
    messagingSenderId: '237814584611',
    projectId: 'quantum-guard-8bddf',
    storageBucket: 'quantum-guard-8bddf.firebasestorage.app',
    androidClientId: '237814584611-7b336lhvtl59id5oicuh7i7ddd1594m1.apps.googleusercontent.com',
    iosClientId: '237814584611-him275523db7373jbcuo9mn47o3mkiqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKMzehywMTCiKhkl2aQpo4crxprxnUu-U',
    appId: '1:237814584611:web:58eafcf8571692950ee896',
    messagingSenderId: '237814584611',
    projectId: 'quantum-guard-8bddf',
    authDomain: 'quantum-guard-8bddf.firebaseapp.com',
    storageBucket: 'quantum-guard-8bddf.firebasestorage.app',
  );

}